networks:
  net:
    external: false

volumes:
  postgres-db:
    external: false

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres-db:/var/lib/postgresql/data
    #  - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    #  - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./initdb:/docker-entrypoint-initdb.d
      - ./datos:/datos
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tpdml
    ports:
      - 5432:5432
    networks:
      - net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  superset:
    image: apache/superset:4.0.0
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - 8088:8088
    depends_on:
      db:
        condition: service_healthy # Aguarda hasta que la base de datos este funcionando correctamente
    networks:
      - net
